DjangoTraining/urls.py
from django.conf.urls import include,url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls'))
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name="polls"
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(), name="detail"),
    url(r'^(?P<pk>[0-9]+)/results/$',views.ResultsView.as_view(), name="results"),
    url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote, name="vote"),
]

polls/models.py
from django.db import models
from django.utils import timezone

import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=50)
    pub_date = models.DateTimeField('date published', default=datetime.datetime.now)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        yesterday = now - datetime.timedelta(days=1)
        return yesterday <= self.pub_date <= now

    was_published_recently.boolean = True

class Choice(models.Model):
    question = models.ForeignKey('Question',on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=50)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic

from .models import Question,Choice

class IndexView(generic.ListView):
    model = Question
    template_name = 'polls/index.html'

    def get_context_data(self):
        latest_questions = Question.objects.order_by('-pub_date')[:5]
        return {'questions' : latest_questions}

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    template_name = 'polls/results.html'
    model = Question
    
def vote(request,question_id):
    selected_choice = request.POST['choice']
    choice = Choice.objects.get(pk=selected_choice)
    choice.votes += 1
    choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=[question_id]))

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice  in question.choice_set.all %}
<p>
  <input type="radio" name="choice" id="choice{{choice.id}}" value="{{choice.id}}">
  <label for="choice{{choice.id}}">{{choice.choice_text}}</label>
</p>
{% endfor %}
<input type="submit" value="Vote"/>
</form>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<ul>
{% for question in questions %}
    <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
{% endfor %}
</ul>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice  in question.choice_set.all %}
    <li>{{choice.choice_text}} -- {{ choice.votes }} vote{{choice.votes|pluralize}}</li>
{% endfor %}
</ul>


<a href="{% url 'polls:detail' question.id %}">Vote again?</a>